language: node_js
node_js:
  - 8.12.0

# S: Build Lifecycle
install:
  - npm install

before_script:
# - npm install -g gulp

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "dayue"
  - git config user.email "x@xiao.ai"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master
env:
  global:
    # Github Pages
    - GH_REF: github.com/DayueOrg/blog.git
